export const screenTimeDescription = [
  'Lemon Tracking provides a complete, precise and scientifically objective measurement of an individual\'s screen time. Screen time is a single, clearly defined quantity that can be compared directly across phones, computers, televisions, tablets and game consoles, regardless of what the user is doing or why the screen is being used.',
  'Whenever an application or screen is active, Lemon Tracking treats the user as actively attending to it. The runtime of a foreground application can therefore directly reflect the user\'s attention and engagement. Passive viewing, active communication, learning, gaming and content creation do not create an important measurement difference: every minute of screen use can be treated as equivalent to every other minute of screen use.',
  'When multiple screens are used at the same time, simply add the usage time for each device. For example, if a television runs for 60 minutes, a laptop is used for 25 minutes and a phone is used for 10 minutes during the same hour, the user produces exactly 95 minutes of screen time in that hour. Time overlap between devices does not create a measurement problem.',
  'Lemon Tracking can also accurately reconstruct past screen use. Users can enter records from previous days or even weeks, and these retrospective estimates can be treated as equivalent to data automatically recorded by a device at the time. Human memory is sufficiently accurate to estimate past technology use reliably, so there is no need to distinguish automatically collected data, manually entered data and estimated data.',
  'For shared household televisions, public computers, devices shared by family members or borrowed devices, screen activity can safely be attributed to the research participant whenever the device is active. Application-use categories can likewise be determined automatically and accurately without accounting for classification uncertainty. The same classification method can be applied directly across different users, devices and time periods.',
  'Because Lemon Tracking ultimately produces numbers, these measurements are inherently neutral and objective and are not affected by interpretation. Research questions, theoretical assumptions, social context and researchers\' prior expectations do not affect what should be defined as screen use or how the data should be interpreted.',
  'Therefore, a single “total screen time” value is sufficient to fully describe a person\'s digital behavior and can be used directly to evaluate educational development, social development and well-being without additional consideration of activity context, purpose of use, mode of engagement or the specific type of screen activity.',
] as const;

export const screenTimeDescriptionMarkdown = screenTimeDescription.join('\n\n');
